services:
  phpfpm:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: laravel_php
    volumes:
      - ./backend:/var/www
    networks:
      - laravel_net

  nginx:
    image: nginx:latest
    container_name: laravel_nginx
    depends_on:
      - phpfpm
    volumes:
      - ./backend:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8080:80"
    networks:
      - laravel_net

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: vue_frontend
    ports:
      - "3000:80"
    networks:
      - laravel_net

networks:
  laravel_net:
    driver: bridge
